### ISSUE TITLE
Segmentation fault in statedb server

### ISSUE THREAD

**Issue by fschoell** [dfuse-io/dfuse-eosio#144]
```
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]: panic: runtime error: invalid memory address or nil pointer dereference
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1ae6b23]
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]: goroutine 403 [running]:
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]: github.com/dfuse-io/dfuse-eosio/statedb/grpc.(*Server).prepareRead(0xc0011a9040, 0x33e4a00, 0xc000b4d890, 0x0, 0x0, 0x1, 0x20, 0x18, 0x203000, 0x203000, ...)
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]:         /tmp/build.1599495789.21285/dfuse-eosio/statedb/grpc/read.go:55 +0x3c3
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]: github.com/dfuse-io/dfuse-eosio/statedb/grpc.(*Server).GetTableRow(0xc0011a9040, 0x33e4a00, 0xc000b4d890, 0xc0011b9800, 0xc0011a9040, 0x1ee7200, 0xc0011a5be0)
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]:         /tmp/build.1599495789.21285/dfuse-eosio/statedb/grpc/get_table_row.go:23 +0x1ff
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]: github.com/dfuse-io/dfuse-eosio/pb/dfuse/eosio/statedb/v1._State_GetTableRow_Handler.func1(0x33e4a00, 0xc000b4d890, 0x2198ba0, 0xc0011b9800, 0xc000b4d890, 0xc00137e5a0, 0xc0011b9e00, 0x0)
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]:         /tmp/build.1599495789.21285/dfuse-eosio/pb/dfuse/eosio/statedb/v1/statedb.pb.go:1513 +0x86
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]: github.com/dfuse-io/dgrpc.setupLoggingInterceptors.func1(0x33e4a00, 0xc000b4d800, 0x2198ba0, 0xc0011b9800, 0xc0011a9c40, 0xc0011a9c60, 0xc0011c3c00, 0x20, 0x0, 0x0)
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]:         /tmp/build.1599495789.21285/go/pkg/mod/github.com/dfuse-io/dgrpc@v0.0.0-20200710191139-bcb9296ceb80/logging.go:71 +0x73
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]: github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x33e4a00, 0xc000b4d800, 0x2198ba0, 0xc0011b9800, 0x33e4a00, 0xc000b4d800, 0xf, 0x0)
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]:         /tmp/build.1599495789.21285/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/chain.go:25 +0x63
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]: github.com/dfuse-io/dgrpc.setupTracingInterceptors.func1(0x33e4a00, 0xc000b4d800, 0x2198ba0, 0xc0011b9800, 0xc0011a9c40, 0xc0011a9c80, 0xc0011c3be0, 0x14, 0x0, 0x0)
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]:         /tmp/build.1599495789.21285/go/pkg/mod/github.com/dfuse-io/dgrpc@v0.0.0-20200710191139-bcb9296ceb80/tracing.go:31 +0x7b
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]: github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x33e4a00, 0xc000b4d800, 0x2198ba0, 0xc0011b9800, 0x29, 0xbfcdf9801fc9f12e, 0x128bdda62, 0x48c13e0)
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]:         /tmp/build.1599495789.21285/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/chain.go:25 +0x63
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]: github.com/grpc-ecosystem/go-grpc-middleware/logging/zap.UnaryServerInterceptor.func1(0x33e4a00, 0xc000b4d530, 0x2198ba0, 0xc0011b9800, 0xc0011a9c40, 0xc0011a9ca0, 0x3, 0x3, 0x33f5280, 0xc0011c1300)
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]:         /tmp/build.1599495789.21285/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/logging/zap/server_interceptors.go:32 +0x10a
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]: github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x33e4a00, 0xc000b4d530, 0x2198ba0, 0xc0011b9800, 0x29, 0xc001105630, 0xc000b4d530, 0xc0006c3970)
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]:         /tmp/build.1599495789.21285/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/chain.go:25 +0x63
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]: github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x33e4a00, 0xc000b4d530, 0x2198ba0, 0xc0011b9800, 0xc0011a9c40, 0xc0011a9cc0, 0x33e4a00, 0xc000b4d530, 0xc0012ca1a8, 0xc000b4d500)
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]:         /tmp/build.1599495789.21285/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0xad
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]: github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x33e4a00, 0xc000b4d530, 0x2198ba0, 0xc0011b9800, 0x29, 0x2198ba0, 0xc0011b9800, 0x0)
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]:         /tmp/build.1599495789.21285/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/chain.go:25 +0x63
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]: github.com/grpc-ecosystem/go-grpc-middleware/tags.UnaryServerInterceptor.func1(0x33e4a00, 0xc000b4ce40, 0x2198ba0, 0xc0011b9800, 0xc0011a9c40, 0xc0011a9ce0, 0xdcebba, 0x2025180, 0xc0011a9d00, 0xc0011a9c40)
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]:         /tmp/build.1599495789.21285/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/tags/interceptors.go:22 +0x86
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]: github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x33e4a00, 0xc000b4ce40, 0x2198ba0, 0xc0011b9800, 0xc0010b6800, 0xc0011a97e0, 0xc0006c3b08, 0x4186d8)
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]:         /tmp/build.1599495789.21285/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/chain.go:25 +0x63
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]: github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x33e4a00, 0xc000b4ce40, 0x2198ba0, 0xc0011b9800, 0xc0011a9c40, 0xc0011a9c60, 0xc000217b78, 0x4a3128, 0x2084660, 0xc000b4ce40)
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]:         /tmp/build.1599495789.21285/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/chain.go:34 +0xd5
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]: github.com/dfuse-io/dfuse-eosio/pb/dfuse/eosio/statedb/v1._State_GetTableRow_Handler(0x2161e20, 0xc0011a9040, 0x33e4a00, 0xc000b4ce40, 0xc00077de00, 0xc0012ecbd0, 0x33e4a00, 0xc000b4ce40, 0xc00090cb70, 0x26)
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]:         /tmp/build.1599495789.21285/dfuse-eosio/pb/dfuse/eosio/statedb/v1/statedb.pb.go:1515 +0x14b
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]: google.golang.org/grpc.(*Server).processUnaryRPC(0xc001706600, 0x3400ec0, 0xc00052ed80, 0xc0010b6800, 0xc0012ecea0, 0x47e1928, 0x0, 0x0, 0x0)
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]:         /tmp/build.1599495789.21285/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1024 +0x501
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]: google.golang.org/grpc.(*Server).handleStream(0xc001706600, 0x3400ec0, 0xc00052ed80, 0xc0010b6800, 0x0)
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]:         /tmp/build.1599495789.21285/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1313 +0xd3d
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00051f3e0, 0xc001706600, 0x3400ec0, 0xc00052ed80, 0xc0010b6800)
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]:         /tmp/build.1599495789.21285/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:722 +0xa1
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]: created by google.golang.org/grpc.(*Server).serveStreams.func1
Sep 08 11:44:00 jungle-flx11s dfuseeos[40274]:         /tmp/build.1599495789.21285/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:720 +0xa1
```

**Comment by fschoell** [comment]
Flags:

```
start:
  args:
    - statedb
  flags:
    config-file: ""
    log-format: text
    log-to-file: false
    common-chain-id: 2a02a0053e5a8cf73a56ba0fda11e4d92e0238a4a2aa74fccf46d5a910746840
    common-blockstream-addr: dns:///blockstream:9000
    common-blocks-store-url: s3://storage:7480/jungle-dfuse-merged-blocks?region=none&insecure=true
    common-blockmeta-addr: dns:///blockmeta:9000
    statedb-http-listen-addr: :8080
    statedb-grpc-listen-addr: :9000
    statedb-store-dsn: tikv://pd1,pd2,pd3:2379/state # kvdb connection string to State database
    statedb-enable-server-mode: true # Enables flux server mode, launch a server
    statedb-enable-inject-mode: false # Enables flux inject mode, writes into its database
    statedb-enable-pipeline: true # Enables statedb without a blocks pipeline, useful for running a development server (**do not** use this in prod)
    statedb-reproc-shard-store-url: s3://storage:7480/jungle-dfuse-v1-reproc-shards?region=none&insecure=true # [BATCH] Storage url where all reproc shard write requests should be written to
    statedb-enable-reproc-sharder-mode: false # [BATCH] Enables flux reproc shard mode, exclusive option, cannot be set if either server, injector or reproc-injector mode is set
    statedb-enable-reproc-injector-mode: false # [BATCH] Enables flux reproc injector mode, exclusive option, cannot be set if either server, injector or reproc-shard mode is set
    statedb-reproc-shard-count: 0 # [BATCH] Number of shards to split in (in 'reproc-sharder' mode), or join (in 'reproc-injector' mode)
    statedb-reproc-shard-start-block-num: 0 # [BATCH] Start processing block logs at this height, must be on a 100-blocks boundary
    statedb-reproc-shard-stop-block-num: 0 # [BATCH] Stop processing block logs at this height, must be on a 100-blocks boundary
    statedb-reproc-injector-shard-index: 0 # [BATCH] Index of the shard to perform injection for, should be lower than shard-count
    statedb-reproc-shard-scratch-directory: "file://{dfuse-data-dir}/statedb/reproc-shards-scratch" # [BATCH] Provide a scratch directory where sharder while write each element composing a shard to a temporary file instead of holding everything in RAM, trade-off between I/O bound and RAM bound
```
