### ISSUE TITLE
cannot sync kylin network - get multiple stack traces

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/dfuse-eosio#85]
Syncing  kylin network, sometime after block 23844312, get the following stack trace

```
goroutine 2367892 [running]:
runtime/debug.Stack(0x0, 0x7fa9f00857f8, 0xc0040a94a0)
#011/usr/lib/go-1.13/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
#011/usr/lib/go-1.13/src/runtime/debug/stack.go:16 +0x22
github.com/eoscanada/eos-go/ecc.CurveID.String(...)
#011/tmp/build.11644/go/pkg/mod/github.com/eoscanada/eos-go@v0.9.1-0.20200616134903-ff2413bdaa99/ecc/curve.go:22
fmt.(*pp).handleMethods(0xc00da33380, 0xc000000073, 0xeb5101)
#011/usr/lib/go-1.13/src/fmt/print.go:630 +0x302
fmt.(*pp).printArg(0xc00da33380, 0x1e03260, 0x3a976bb, 0x73)
#011/usr/lib/go-1.13/src/fmt/print.go:713 +0x206
fmt.(*pp).doPrintf(0xc00da33380, 0x21bfd03, 0x18, 0xc00014de30, 0x1, 0x1)
#011/usr/lib/go-1.13/src/fmt/print.go:1030 +0x15b
fmt.Errorf(0x21bfd03, 0x18, 0xc00014de30, 0x1, 0x1, 0x40, 0x38)
#011/usr/lib/go-1.13/src/fmt/errors.go:20 +0x77
github.com/eoscanada/eos-go.(*Decoder).ReadSignature(0xc00014f330, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0040a94a0)
#011/tmp/build.11644/go/pkg/mod/github.com/eoscanada/eos-go@v0.9.1-0.20200616134903-ff2413bdaa99/decoder.go:984 +0x736
github.com/eoscanada/eos-go.(*ABI).read(0xc0154567e0, 0xc00014f330, 0xc01171bed0, 0x9, 0xc01171bee0, 0x9, 0xc0040a94a0, 0x155, 0x1e0, 0xc0040a94a0, ...)
#011/tmp/build.11644/go/pkg/mod/github.com/eoscanada/eos-go@v0.9.1-0.20200616134903-ff2413bdaa99/abidecoder.go:369 +0x29bd
github.com/eoscanada/eos-go.(*ABI).resolveField(0xc0154567e0, 0xc00014f330, 0xc01171bed0, 0x9, 0xc01171bee0, 0x9, 0xc0040a94a0, 0x155, 0x1e0, 0xc0040a94a0, ...)
#011/tmp/build.11644/go/pkg/mod/github.com/eoscanada/eos-go@v0.9.1-0.20200616134903-ff2413bdaa99/abidecoder.go:156 +0x2aa
github.com/eoscanada/eos-go.(*ABI).decodeFields(0xc0154567e0, 0xc00014f330, 0xc00629a280, 0xa, 0xa, 0x3b66490, 0x0, 0x0, 0x1b0, 0x1d17ac0, ...)
#011/tmp/build.11644/go/pkg/mod/github.com/eoscanada/eos-go@v0.9.1-0.20200616134903-ff2413bdaa99/abidecoder.go:80 +0xd6
github.com/eoscanada/eos-go.(*ABI).decode(0xc0154567e0, 0xc00075d330, 0xc006268230, 0x6, 0x0, 0xc0154567e0, 0x0, 0x0, 0x0)
#011/tmp/build.11644/go/pkg/mod/github.com/eoscanada/eos-go@v0.9.1-0.20200616134903-ff2413bdaa99/abidecoder.go:73 +0x198
github.com/eoscanada/eos-go.(*ABI).Decode(...)
#011/tmp/build.11644/go/pkg/mod/github.com/eoscanada/eos-go@v0.9.1-0.20200616134903-ff2413bdaa99/abidecoder.go:42
github.com/dfuse-io/dfuse-eosio/codec.(*decodingQueue).decodeAction(0xc0044e2ce0, 0xc011b42b00, 0xffffffffffffffff, 0xc006cae1c0, 0x40, 0x16bd660, 0x0, 0xc006b65680, 0x0)
#011/tmp/build.11644/dfuse-eosio/codec/abi_decoder.go:518 +0x116e
github.com/dfuse-io/dfuse-eosio/codec.(*decodingQueue).executeDecodingJob(0xc0044e2ce0, 0x2737f60, 0xc0000e2010, 0xc0067ab990, 0x1, 0x1, 0x0, 0x0, 0x4398fa, 0x0, ...)
#011/tmp/build.11644/dfuse-eosio/codec/abi_decoder.go:434 +0x378
github.com/dfuse-io/dhammer.(*Hammer).processBatch(0xc00583e380, 0x2737f60, 0xc0000e2010, 0xc0067ab990, 0x1, 0x1, 0xc018f6cea0)
#011/tmp/build.11644/go/pkg/mod/github.com/dfuse-io/dhammer@v0.0.0-20200430014759-1292c689a063/dhammer.go:164 +0xba
created by github.com/dfuse-io/dhammer.(*Hammer).runInput
#011/tmp/build.11644/go/pkg/mod/github.com/dfuse-io/dhammer@v0.0.0-20200430014759-1292c689a063/dhammer.go:152 +0x41a
2020-07-08T16:36:10.119Z (abi_decoder) skipping action since we were not able to decode it against ABI (codec/abi_decoder.go:527){"block_num": 23844448, "trx_id": "59e46f42470d43179d9e0f03df4da86744657aac2eccc3f2730c16c1f3c00b92", "action": "pokereosgame:reveal", "global_sequence": 18446744073709551615, "error": "read: unsupported curve ID: UN"}
goroutine 2367894 [running]:
runtime/debug.Stack(0x0, 0x1e0, 0xc00545c1e0)
... etc
```

Dfuse runs into more problems and chain cannot be synced.

Full log file sent privately

**Comment by maoueh** [comment]
The printed stack trace was a debugging left over. This is fixed in eos-go library, I'll fix the panic issue and then bump everything.
